name: google_maps_plugin
description: A Flutter plugin for integrating Google Maps in iOS and Android applications.
repository: https://github.com/flutter/packages/tree/main/packages/google_maps_plugin/google_maps_plugin
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+maps%22
version: 2.5.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

flutter:
  plugin:
    implements: google_maps_plugin
    platforms:
      android:
        package: io.flutter.plugins.googlemaps
        pluginClass: GoogleMapsPlugin
        dartPluginClass: GoogleMapsFlutterAndroid
      ios:
        pluginClass: FLTGoogleMapsPlugin
        dartPluginClass: GoogleMapsFlutterIOS

dependencies:
  flutter:
    sdk: flutter
  stream_transform:
  plugin_platform_interface:
  flutter_plugin_android_lifecycle:

dev_dependencies:
  flutter_test:
    sdk: flutter


topics:
  - google-maps
  - google-maps-flutter
  - map

# The example deliberately includes limited-use secrets.
false_secrets:
  - /example/web/index.html
